### ISSUE TITLE
Back button doesn't play nicely with applications

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#27] opened 2015-06-23 16:32 UTC
Using the back button to leave an application causes it to crash/restart on resume.

Currently all the samples I build are crashing on launch from the debugger, so I can't test this with a wide range of samples.

**Comment by simongeilfus** [comment] 2015-07-02 09:24
Hey guys,

Yes I can confirm that something weird is happening when resuming an app after pressing the back button.

At first I was thinking about some issue with the OpenGL context, but it seems to be a bit more subtle than this. Am I right thinking the app is doing something like re-calling the setup instead of destroying everything and restarting fresh? I'll investigate a bit more, but it seems that the crash I have when it resume is linked to some objects not being properly initialised.

**Comment by chaoticbob** [comment] 2015-07-19 09:32
Fixed in the latest commits. This had to do when the camera singleton the C++ side when the Back button was pressed. It issues an *almost* full app exit.

**Closed** 2015-07-19 09:33 UTC
